# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#030810"

# Main text color
theme[main_fg]="#ffffff"

# Title color for boxes
theme[title]="#8ab9db"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ABD0E2"

# Background color of selected item in processes box
theme[selected_bg]="#283851"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#283851"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8ab9db"

# Box outline and divider line color
theme[cpu_box]="#7eb9b1"
theme[mem_box]="#7eb9b1"
theme[net_box]="#7eb9b1"
theme[proc_box]="#7eb9b1"
theme[div_line]="#283851"

# Gradient for all meters and graphs
theme[temp_start]="#ABD0E2"
theme[temp_mid]="#90adc5"
theme[temp_end]="#7eb9b1"


theme[cpu_start]="#ABD0E2"
theme[cpu_mid]="#90adc5"
theme[cpu_end]="#7eb9b1"


theme[free_start]="#90adc5"
theme[free_mid]="#C6DBE5"
theme[free_end]="#C6DBE5"


theme[cached_start]="#C6DBE5"
theme[cached_mid]="#C6DBE5"
theme[cached_end]="#C6DBE5"


theme[available_start]="#ABD0E2"
theme[available_mid]="#ABD0E2"
theme[available_end]="#ABD0E2"


theme[used_start]="#7eb9b1"
theme[used_mid]="#7eb9b1"
theme[used_end]="#7eb9b1"


theme[download_start]="#C6DBE5"
theme[download_mid]="#ABD0E2"
theme[download_end]="#90adc5"


theme[upload_start]="#C6DBE5"
theme[upload_mid]="#ABD0E2"
theme[upload_end]="#90adc5"