# Change the default Omarchy look'n'feel

# Purple
# $activeBorderColor = rgb(8858a5) rgb(8858a5) rgb(8858a5) rgb(8858a5) rgb(bb81bb) rgb(8858a5) rgb(8858a5) rgb(8858a5) rgb(8858a5) rgb(8858a5) 35deg
# Green
$activeBorderColor = rgb(a4be7a) rgb(a4be7a) rgb(a4be7a) rgb(a4be7a) rgb(d4ee8f) rgb(a4be7a) rgb(a4be7a) rgb(a4be7a) rgb(a4be7a) rgb(a4be7a) 35deg

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2       # Default: 0
    gaps_out = 0      # Default: commented
    border_size = 4   # Default: 0
    #col.active_border = rgba(200,33,33,1)  # TrackPoint Red
    col.active_border = $activeBorderColor
    # Purple
    col.inactive_border = rgba(8858a5ff)
    # Green
    #col.inactive_border = rgba(a4be7aff)


    # Use master layout instead of dwindle
    # layout = master
}

group {
    col.border_active = $activeBorderColor
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 20
    rounding_power = 1.3
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
    bezier = easeInOutQuant, 0.76, 0, 0.24, 1
    bezier = linear, 0, 0, 1, 1

    animation = border, 1, 1, linear
    animation = borderangle, 1, 142, linear, loop
  }
